-- ============================================================
-- QuestWork 퀘스트 시드 데이터 (20개)
-- 실행: DELETE FROM quests; 후 이 파일 실행
-- ============================================================

DELETE FROM quests;

INSERT INTO quests (manager_id, title, form_data, reward_amount, deadline, status, created_at, updated_at) VALUES
(1, 'React + TypeScript 관리자 대시보드 개발', '{"description":"중소규모 SaaS 서비스의 운영자용 대시보드를 구현합니다.\n\n## 요구사항\n- 사용자 통계 카드 (월별 가입, DAU, 전환율)\n- 거래 내역 테이블 (정렬, 필터, 페이지네이션)\n- Chart.js 기반 매출 꺾은선 그래프\n- 반응형 레이아웃 (PC / 태블릿)\n- Storybook 컴포넌트 문서 포함","techStack":["React","TypeScript","Tailwind CSS","Chart.js","Storybook"],"difficulty":"Advanced","submissionFormats":["github","url","file"]}', 1500000, '2026-06-20 23:59:59', 'OPEN', NOW(), NOW()),
(1, 'Next.js 블로그 플랫폼 풀스택 구현', '{"description":"MDX 기반 정적 블로그 플랫폼을 Next.js App Router로 구현합니다.\n\n## 요구사항\n- MDX 파일 기반 포스트 렌더링\n- 태그/카테고리 필터\n- 전문 검색 (Algolia 또는 Flexsearch)\n- SEO 메타태그 자동 생성\n- 다크모드 지원","techStack":["Next.js","TypeScript","MDX","Tailwind CSS","Algolia"],"difficulty":"Intermediate","submissionFormats":["github","url"]}', 1200000, '2026-06-15 23:59:59', 'OPEN', NOW(), NOW()),
(1, 'Spring Boot REST API 서버 구축 (JWT 인증 포함)', '{"description":"JWT 인증이 포함된 RESTful API 서버를 설계하고 구현합니다.\n\n## 요구사항\n- JWT Access / Refresh Token 발급 및 갱신\n- Spring Security 기반 권한 제어\n- JPA + QueryDSL로 동적 검색 API\n- Swagger(OpenAPI 3.0) 문서 자동 생성\n- 단위 테스트 커버리지 70% 이상","techStack":["Spring Boot","Java","JPA","QueryDSL","Spring Security","JWT"],"difficulty":"Advanced","submissionFormats":["github","file"]}', 1800000, '2026-06-25 23:59:59', 'OPEN', NOW(), NOW()),
(1, 'Flutter 크로스플랫폼 가계부 앱 개발', '{"description":"Flutter로 iOS / Android 동시 지원 가계부 앱을 제작합니다.\n\n## 요구사항\n- 수입/지출 CRUD\n- 월별 통계 파이 차트 (fl_chart)\n- 카테고리 태그 관리\n- SQLite 로컬 저장\n- 다크모드 지원","techStack":["Flutter","Dart","SQLite","fl_chart"],"difficulty":"Intermediate","submissionFormats":["github","file"]}', 1000000, '2026-06-17 23:59:59', 'OPEN', NOW(), NOW()),
(1, 'Vue 3 + Pinia 이커머스 장바구니 UI 구현', '{"description":"Vue 3 Composition API와 Pinia 상태관리로 장바구니 기능을 구현합니다.\n\n## 요구사항\n- 상품 목록 / 상세 페이지\n- 장바구니 추가·삭제·수량 변경\n- 쿠폰 코드 적용 로직\n- 결제 페이지 UI\n- Vue Test Utils 기반 단위 테스트","techStack":["Vue 3","TypeScript","Pinia","Vitest","Tailwind CSS"],"difficulty":"Intermediate","submissionFormats":["github","url"]}', 900000, '2026-06-13 23:59:59', 'OPEN', NOW(), NOW()),
(1, 'FastAPI + PostgreSQL 퀴즈 API 서버 개발', '{"description":"FastAPI로 퀴즈 플랫폼 백엔드 API를 구축합니다.\n\n## 요구사항\n- 퀴즈셋 CRUD (SQLAlchemy + Alembic 마이그레이션)\n- 사용자별 응시 기록 저장\n- 점수 계산 및 랭킹 API\n- OAuth2 Password Flow 인증\n- pytest 커버리지 80% 이상","techStack":["FastAPI","Python","PostgreSQL","SQLAlchemy","Docker"],"difficulty":"Advanced","submissionFormats":["github","file"]}', 1300000, '2026-06-23 23:59:59', 'OPEN', NOW(), NOW()),
(1, '워드프레스 Gutenberg 호환 커스텀 테마 개발', '{"description":"Gutenberg 블록 편집기와 완전히 호환되는 커스텀 워드프레스 테마를 개발합니다.\n\n## 요구사항\n- FSE(Full Site Editing) 지원\n- 블록 패턴 10종 이상 등록\n- 모바일 퍼스트 반응형 디자인\n- WooCommerce 기본 스타일 호환","techStack":["WordPress","PHP","Gutenberg","WooCommerce","SCSS"],"difficulty":"Intermediate","submissionFormats":["url","file"]}', 800000, '2026-06-10 23:59:59', 'OPEN', NOW(), NOW()),
(1, 'React Native 위치 기반 맛집 추천 앱 MVP', '{"description":"현재 위치를 기반으로 주변 맛집을 추천하는 React Native MVP를 제작합니다.\n\n## 요구사항\n- Expo Location API로 현재 위치 수집\n- Kakao Map API 연동 지도 표시\n- 카테고리 필터 (한식·중식·일식·기타)\n- 즐겨찾기 로컬 저장 (AsyncStorage)","techStack":["React Native","Expo","Kakao Map API","TypeScript"],"difficulty":"Intermediate","submissionFormats":["github","file"]}', 1100000, '2026-06-16 23:59:59', 'OPEN', NOW(), NOW()),
(1, 'Node.js 실시간 채팅 서버 구현 (Socket.IO)', '{"description":"Socket.IO를 활용한 실시간 채팅 서버와 웹 클라이언트를 구현합니다.\n\n## 요구사항\n- 다중 채팅방 생성/입장/퇴장\n- 닉네임 기반 참여\n- 이모지 반응 기능\n- Redis Pub/Sub 기반 수평 확장 지원\n- Jest 기반 단위 테스트","techStack":["Node.js","Socket.IO","Redis","Express","Jest"],"difficulty":"Intermediate","submissionFormats":["github","url"]}', 950000, '2026-06-11 23:59:59', 'OPEN', NOW(), NOW()),
(1, 'Django REST Framework 예약 시스템 API', '{"description":"병원 또는 스터디룸 예약 시스템을 Django REST Framework으로 구축합니다.\n\n## 요구사항\n- 예약 슬롯 생성 및 조회\n- 예약 충돌 방지 로직\n- 이메일 알림 (Celery + SendGrid)\n- drf-yasg Swagger 문서\n- 80% 이상 테스트 커버리지","techStack":["Django","Python","DRF","Celery","PostgreSQL"],"difficulty":"Advanced","submissionFormats":["github","file"]}', 1400000, '2026-06-21 23:59:59', 'OPEN', NOW(), NOW()),
(1, 'Svelte 기반 개발자 포트폴리오 템플릿 제작', '{"description":"프리랜서 개발자를 위한 Svelte 포트폴리오 템플릿을 제작합니다.\n\n## 요구사항\n- 자기소개·프로젝트·기술스택·연락처 섹션\n- JSON 설정 파일로 쉬운 커스터마이징\n- 애니메이션 전환 효과 (svelte/transition)\n- OG 메타태그 지원\n- MIT 오픈소스 라이선스","techStack":["Svelte","SvelteKit","TypeScript","CSS"],"difficulty":"Beginner","submissionFormats":["github","url"]}', 600000, '2026-06-09 23:59:59', 'OPEN', NOW(), NOW()),
(1, 'Kotlin Jetpack Compose 할일 관리 앱 개발', '{"description":"Jetpack Compose와 Room DB를 활용한 할일 관리 Android 앱을 개발합니다.\n\n## 요구사항\n- 할일 CRUD (Room 로컬 저장)\n- 우선순위·마감일 설정\n- WorkManager 기반 마감 알림\n- MVVM + Clean Architecture\n- UI 테스트 (Espresso)","techStack":["Kotlin","Jetpack Compose","Room","WorkManager","MVVM"],"difficulty":"Intermediate","submissionFormats":["github","file"]}', 1100000, '2026-06-18 23:59:59', 'OPEN', NOW(), NOW()),
(1, 'Three.js 인터랙티브 3D 랜딩페이지 제작', '{"description":"Three.js를 활용해 스크롤 인터랙션이 있는 3D 제품 랜딩페이지를 제작합니다.\n\n## 요구사항\n- GSAP ScrollTrigger 연동 카메라 이동\n- glTF 3D 모델 로드 및 조작\n- 파티클 배경 효과\n- 모바일 최적화\n- 로딩 화면 포함","techStack":["Three.js","JavaScript","GSAP","Vite","WebGL"],"difficulty":"Advanced","submissionFormats":["github","url","file"]}', 1600000, '2026-06-25 23:59:59', 'OPEN', NOW(), NOW()),
(1, 'WooCommerce 포인트 적립 플러그인 개발', '{"description":"포인트 적립 및 등급별 할인 기능을 제공하는 WooCommerce 확장 플러그인을 개발합니다.\n\n## 요구사항\n- 구매 금액 대비 포인트 자동 적립\n- 회원 등급 4단계 (브론즈/실버/골드/다이아)\n- 등급별 추가 할인 쿠폰 자동 발급\n- 관리자 포인트 수동 조정 페이지\n- WC HPOS 호환","techStack":["PHP","WordPress","WooCommerce","MySQL"],"difficulty":"Advanced","submissionFormats":["file","url"]}', 1200000, '2026-06-22 23:59:59', 'OPEN', NOW(), NOW()),
(1, 'TypeScript CLI 프로젝트 스캐폴딩 툴 개발', '{"description":"프로젝트 보일러플레이트를 자동으로 생성해 주는 CLI 툴을 TypeScript로 개발합니다.\n\n## 요구사항\n- 대화형 프롬프트 (Inquirer.js)\n- React / Vue / Express 템플릿 지원\n- npm 패키지로 배포 (npx 실행 가능)\n- Vitest 단위 테스트\n- GitHub Actions CI 포함","techStack":["TypeScript","Node.js","Inquirer.js","Vitest","GitHub Actions"],"difficulty":"Intermediate","submissionFormats":["github","url"]}', 700000, '2026-06-12 23:59:59', 'OPEN', NOW(), NOW()),
(1, 'iOS Swift SwiftUI 날씨 앱 개발', '{"description":"OpenWeatherMap API를 활용한 SwiftUI 날씨 앱을 개발합니다.\n\n## 요구사항\n- CoreLocation 현재 위치 날씨\n- 도시 검색 기능\n- 7일 예보 시각화\n- WidgetKit 위젯 지원\n- 한국어·영어 다국어 지원","techStack":["Swift","SwiftUI","CoreLocation","WidgetKit","Xcode"],"difficulty":"Intermediate","submissionFormats":["github","file"]}', 1300000, '2026-06-19 23:59:59', 'OPEN', NOW(), NOW()),
(1, 'Rust WebAssembly 이미지 필터 라이브러리', '{"description":"Rust로 이미지 필터 알고리즘을 구현하고 WebAssembly로 컴파일하여 브라우저에서 활용할 수 있도록 합니다.\n\n## 요구사항\n- 그레이스케일·세피아·블러·엣지 감지 필터\n- wasm-bindgen으로 JS 바인딩\n- Canvas API 연동 데모 페이지\n- npm 패키지 배포 준비\n- JS 대비 성능 벤치마크","techStack":["Rust","WebAssembly","wasm-bindgen","JavaScript","Canvas API"],"difficulty":"Advanced","submissionFormats":["github","url","file"]}', 2000000, '2026-07-01 23:59:59', 'OPEN', NOW(), NOW()),
(1, 'React UI 컴포넌트 라이브러리 구축 및 배포', '{"description":"React 기반 재사용 가능한 UI 컴포넌트 라이브러리를 구축합니다.\n\n## 요구사항\n- Button / Input / Modal / Dropdown 등 15종 이상\n- Radix UI Primitives 기반 접근성 준수\n- Storybook 8 + Chromatic 비주얼 테스트\n- CSS Variables 토큰 기반 테마 시스템\n- npm 배포","techStack":["React","TypeScript","Radix UI","Storybook","Chromatic"],"difficulty":"Advanced","submissionFormats":["github","url"]}', 1700000, '2026-06-24 23:59:59', 'OPEN', NOW(), NOW()),
(1, 'Python 채용공고 크롤러 및 데이터 파이프라인', '{"description":"채용 공고 데이터를 수집하고 정제하여 데이터베이스에 저장하는 파이프라인을 구축합니다.\n\n## 요구사항\n- Playwright 기반 동적 페이지 크롤링\n- 데이터 정제 및 중복 제거 로직\n- PostgreSQL 저장 및 스키마 설계\n- Apache Airflow DAG 스케줄링\n- Grafana 모니터링 대시보드","techStack":["Python","Playwright","PostgreSQL","Apache Airflow","Grafana"],"difficulty":"Advanced","submissionFormats":["github","file"]}', 1900000, '2026-06-28 23:59:59', 'OPEN', NOW(), NOW()),
(1, 'HTML/CSS 반응형 이메일 템플릿 10종 제작', '{"description":"뉴스레터·거래 확인·환영·비밀번호 재설정 등 목적별 이메일 HTML 템플릿을 제작합니다.\n\n## 요구사항\n- 10가지 목적별 이메일 템플릿\n- Gmail/Outlook/Apple Mail 렌더링 테스트 통과\n- 테이블 레이아웃 기반 크로스 클라이언트 호환\n- 다크모드 지원 (prefers-color-scheme)\n- Litmus 또는 Email on Acid 테스트","techStack":["HTML","CSS","Email Design","Responsive Design"],"difficulty":"Beginner","submissionFormats":["file","url"]}', 500000, '2026-06-05 23:59:59', 'OPEN', NOW(), NOW());
